### ISSUE TITLE
Ember 2.0.0-beta.1: Cannot read property 'modal-main' of undefined

### ISSUE THREAD

**Issue by alekspetrov** [ATMartin/simple-modal-tutorial#1]
Can't figure out how to make it work with ember.2.0.0-beta.1. This works just fine in Ember 1.11, after install ember beta cannot define property 'modal-main'. Did you try this great solution with ember beta?

**Comment by ATMartin** [comment]
I haven't tried it on beta yet, no. I'll see about making a new branch and moving it over soon, though - thanks for opening this issue!

**Comment by alekspetrov** [comment]
The trouble is that View removed in ember 1.13. I lost sight of it. 
But I can't figure out how to replace `var modal = Ember.VIew.views[target]` in ember 1.13. 

Ref: http://emberjs.com/deprecations/v1.x/#toc_ember-view

**Comment by ATMartin** [comment]
http://blog.atmartin.io/a-simple-modal-for-ember-v2-component-edition/

**Comment by ATMartin** [comment]
Thanks again! :) New code is on branch `ember2`.
